name: Pull Request CI

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-version: [3.2, 3.5, 3.10]

    steps:
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }

      - name: Run unit tests
        run: |
        python -m unittest discover -s . -p 'test_*.py'
